# Site settings
title: Some site title
email: name@email.com
description: >
    This is a section in the config for a description to go. I am filler text. I am filler text.
    I am filler text. I am filler text. I am filler text. I am filler text.
    I am filler text. I am filler text. I am filler text. I am filler text.
    I am filler text. I am filler text. I am filler text. I am filler text.
    I am filler text. I am filler text.
baseurl: "/GabeBellowe" # the subpath of your site, e.g. /blog/
url: "http://nbellowe.com" # the base hostname & protocol for your site
images:
    - "p1-3b2fl.png"
    - "p1-3flTH.png"
    - "p1-4flsq.png"
    - "p1-Alterego.png"
    - "p1-BreckDeck.png"
    - "p1-Brickstacking.png"
    - "p1-ColonialTest.png"
    - "p1-Commercial-1.png"
    - "p1-Commercial-2.png"
    - "p1-GWU.png"
    - "p1-Sketchbk1.png"
    - "p1-Sketchbk2.png"
    - "p1-Sketchbk3.png"
    - "p1-Sketchbk4.png"
    - "p1-Stairtest.png"
    - "p1-Various.png"

# Build settings
markdown: kramdown
